# -*- coding: utf-8 -*-
"""Flames6789.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cu4HvngkFJ1gFdWu2rVj6FvXm422CH2C
"""

import streamlit as st
import time

# --- PAGE CONFIGURATION ---
st.set_page_config(page_title="FLAMES | Relationship Predictor", page_icon="❤️", layout="centered")

# --- CUSTOM STYLING ---
st.markdown("""
    <style>
    .main {
        background-color: #FFCCCB;
    }
    .stButton>button {
        width: 100%;
        border-radius: 20px;
        height: 3em;
        background-color: #FF4B4B;
        color: white;
        font-weight: bold;
        border: none;
    }
    .stButton>button:hover {
        background-color: #ff3333;
        border: none;
        color: white;
    }
    .result-text {
        font-size: 40px;
        font-weight: bold;
        text-align: center;
        color: #FF4B4B;
        padding: 20px;
        border-radius: 10px;
        background: white;
        box-shadow: 0px 4px 15px rgba(0,0,0,0.1);
    }
    </style>
    """, unsafe_allow_html=True)


# --- CORE LOGIC (Place your code here) ---
def calculate_flames(n1, n2):
    name1 = n1.lower().replace(" ", "")
    name2 = n2.lower().replace(" ", "")

    for char in name1[:]:
        if char in name2:
            name1 = name1.replace(char, "", 1)
            name2 = name2.replace(char, "", 1)

    count = len(name1) + len(name2)
    res = ["Friends", "Lovers", "Affectionate", "Marriage", "Enemies", "Siblings"]

    if count > 0:
        while len(res) > 1:
            split_index = (count % len(res) - 1)
            if split_index >= 0:
                right = res[split_index + 1:]
                left = res[:split_index]
                res = right + left
            else:
                res = res[:len(res) - 1]
        return res[0]
    return "Soulmates"

# --- APP UI ---
st.title("🔥 FLAMES: The Love Calculator")
st.write("Enter two names below to discover the destiny of your relationship!")

col1, col2 = st.columns(2)

with col1:
    user_name = st.text_input("Your Name", placeholder="e.g. Romeo")

with col2:
    crush_name = st.text_input("Crush's Name", placeholder="e.g. Juliet")

if st.button("Calculate Destiny"):
    if user_name and crush_name:
        with st.spinner('Consulting the stars...'):
            time.sleep(1.5) # Add a little suspense
            result = calculate_flames(user_name, crush_name)

        # Display Result with Visual Flair
        st.balloons()
        st.markdown(f"<div class='result-text'>✨ {result.upper()} ✨</div>", unsafe_allow_html=True)

        # Contextual Messages
        messages = {
            "Friends": "A bond that lasts forever! 🤝",
            "Lovers": "True love is in the air! 💖",
            "Affectionate": "Someone's got a crush! 😊",
            "Marriage": "Better start planning the wedding! 💍",
            "Enemies": "Keep your distance! ⚡",
            "Siblings": "It's a family affair! 🏠"
        }
        st.info(messages.get(result, "Destiny is mysterious!"))
    else:
        st.error("Please enter both names to proceed!")

# --- FOOTER ---
st.sidebar.markdown("---")
st.sidebar.write("Created with ❤️ using Streamlit")
