# -*- coding: utf-8 -*-
"""Flames1233444555.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SmlydZ1eDWMclnUNT_UAP0TmwpgMNp9w
"""

import streamlit as st
a=list(st.text_input("enter first name").lower())
b=list(st.text_input("enter second name").lower())
for i in a.copy():
    if i in b:
        a.remove(i)
        b.remove(i)
n=len(a+b)
s="flames"
while(len(s)!=1):
    i=n%len(s)-1
    if i==-1:
        s=s[:len(s)-1]
    else:
        s=s[i+1:]+s[:i]
d={'f':'Friends','l':'Love','a':'Affection','m':'Marriage','e':'Engaged','s':'Siblings'}
if(st.button("get results")):
    st.success(d[s])